version: '3.3'

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    image: nushtosh/foodgram_back:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/code/static
      - media_value:/code/media
    depends_on:
      - db


  frontend:
    image: nushtosh/foodgram_front:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/:/usr/share/nginx/html/api/docs
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build: