version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "python manage.py makemigrations --noinput
      && python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && python from_csv_tags.py
      && python from_csv_ingredients.py
      && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/  
    depends_on:
      - db
    env_file:
      - ../backend/.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend
      - frontend
