version: '3.3'

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/code/static
      - media_value:/code/media
    depends_on:
      - db


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../frontend/:/app/result_build


  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/:/usr/share/nginx/html/api/docs
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: