# Generated by Django 3.2.5 on 2022-01-10 18:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добовления')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('add_date',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Место для названия', max_length=150, verbose_name='Название')),
                ('measurement_unit', models.CharField(choices=[('веточка', 'веточка'), ('горсть', 'горсть'), ('пучок', 'пучок'), ('кусок', 'кусок'), ('банка', 'банка'), ('упаковка', 'упаковка'), ('батон', 'батон'), ('л', 'л'), ('стакан', 'стакан'), ('долька', 'долька'), ('щепотка', 'щепотка'), ('по вкусу', 'по вкусу'), ('мл', 'мл'), ('г', 'г'), ('кг', 'кг'), ('шт.', 'шт.'), ('ч. л.', 'ч. л.'), ('ст. л.', 'ст. л.'), ('капля', 'капля'), ('бутылка', 'бутылка'), ('зубчик', 'зубчик')], help_text='Впиши нужную еденицу измерения', max_length=150, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0.0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингридиенты в рецепте',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название рецепта', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(help_text='Добавь картинку', upload_to='images', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Добавь описание', verbose_name='Описание')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Добавь время приготовления', verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Место для названия', max_length=150, unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#49B64E', help_text='Выбери цвет', max_length=18, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(help_text='Нужен уникальный слаг', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добовления')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ('add_date',),
            },
        ),
    ]
